repos:
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.4  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
        stages: [pre-commit]


  # Lint commit message following conventional-commit convention
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.4.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
